Repository Gwamegis/Moya-Android, pull requests merged in 2024-02, with the labels that each got.

#50 [Feat][#47] - 공지 Bottomsheet UI
  app/src/main/java/com/soi/moya/ui/component/NoticeTitleView.kt
  app/src/main/java/com/soi/moya/ui/notice/NewFeatureNotice.kt
  app/src/main/java/com/soi/moya/ui/notice/NoticeScreen.kt
  app/src/main/java/com/soi/moya/ui/theme/MoyaFont.kt
Labels: feature 🌟, inProgress 🦖

#54 #52 [Feat] - 화면 연결 및 팀 선택 연동
  app/build.gradle
  app/src/main/java/com/soi/moya/data/OfflineItemsRepository.kt
  app/src/main/java/com/soi/moya/data/StoredMusicDatabase.kt
  app/src/main/java/com/soi/moya/data/StoredMusicRepository.kt
  app/src/main/java/com/soi/moya/models/Music.kt
  app/src/main/java/com/soi/moya/models/Team.kt
  app/src/main/java/com/soi/moya/repository/MusicPlayerManager.kt
  app/src/main/java/com/soi/moya/ui/AppViewModelProvider.kt
  app/src/main/java/com/soi/moya/ui/UIConsts.kt
  app/src/main/java/com/soi/moya/ui/Utility.kt
  app/src/main/java/com/soi/moya/ui/bottom_nav/BottomNavScreen.kt
  app/src/main/java/com/soi/moya/ui/listItem_menu/ListItemMenuScreen.kt
  app/src/main/java/com/soi/moya/ui/listItem_menu/ListItemMenuViewModel.kt
  app/src/main/java/com/soi/moya/ui/music_list/MusicListScreen.kt
  app/src/main/java/com/soi/moya/ui/music_list/MusicListViewModel.kt
  app/src/main/java/com/soi/moya/ui/music_player/MusicPlayerScreen.kt
  app/src/main/java/com/soi/moya/ui/music_player/MusicPlayerViewModel.kt
  app/src/main/java/com/soi/moya/ui/music_storage/MusicStorageScreen.kt
  app/src/main/java/com/soi/moya/ui/music_storage/MusicStorageViewModel.kt
  app/src/main/java/com/soi/moya/ui/search/SearchScreen.kt
  app/src/main/java/com/soi/moya/ui/select_team/SelectTeamScreen.kt
  app/src/main/res/drawable-nodpi/favorite.png
  app/src/main/res/drawable-nodpi/favorite_cancle.png
  app/src/main/res/drawable-nodpi/player_doosan.png
  app/src/main/res/drawable-nodpi/player_hanwha.png
  app/src/main/res/drawable-nodpi/player_kia.png
  app/src/main/res/drawable-nodpi/player_kiwoom.png
  app/src/main/res/drawable-nodpi/player_kt.png
  app/src/main/res/drawable-nodpi/player_lg.png
  app/src/main/res/drawable-nodpi/player_lotte.png
  app/src/main/res/drawable-nodpi/player_nc.png
  app/src/main/res/drawable-nodpi/player_samsung.png
  app/src/main/res/drawable-nodpi/player_ssg.png
  app/src/main/res/values/strings.xml
Labels: feature 🌟

#59 [Feat] 음악 데이터 연결
  app/src/main/java/com/soi/moya/data/MusicManager.kt
  app/src/main/java/com/soi/moya/models/Music.kt
  app/src/main/java/com/soi/moya/ui/music_list/MusicListViewModel.kt
  app/src/main/java/com/soi/moya/ui/search/SearchViewModel.kt
Labels: feature 🌟, done ✅

#61 #58 [Feat] - backbutton 앱 종료
  app/src/main/java/com/soi/moya/ui/MainActivity.kt
  app/src/main/res/values/strings.xml
Labels: feature 🌟, done ✅

#63 #56 [Feat] - 음악 재생
  app/build.gradle
  app/src/main/java/com/soi/moya/data/MusicManager.kt
  app/src/main/java/com/soi/moya/models/Music.kt
  app/src/main/java/com/soi/moya/models/Team.kt
  app/src/main/java/com/soi/moya/repository/MusicPlayerManager.kt
  app/src/main/java/com/soi/moya/ui/AppViewModelProvider.kt
  app/src/main/java/com/soi/moya/ui/UIConsts.kt
  app/src/main/java/com/soi/moya/ui/bottom_nav/BottomNavScreen.kt
  app/src/main/java/com/soi/moya/ui/component/MusicListItem.kt
  app/src/main/java/com/soi/moya/ui/music_list/MusicListScreen.kt
  app/src/main/java/com/soi/moya/ui/music_list/MusicListViewModel.kt
  app/src/main/java/com/soi/moya/ui/music_player/MusicPlayerScreen.kt
  app/src/main/java/com/soi/moya/ui/music_player/MusicPlayerViewModel.kt
  app/src/main/java/com/soi/moya/ui/music_storage/MusicStorageScreen.kt
  app/src/main/java/com/soi/moya/ui/search/SearchScreen.kt
  app/src/main/java/com/soi/moya/ui/search/SearchViewModel.kt
Labels: feature 🌟

#64 [Feat] 현재 선택한 팀 활성화
  app/src/main/java/com/soi/moya/ui/select_team/SelectTeamViewModel.kt
Labels: feature 🌟

#66 선택한 팀 정보 없는 경우 처리
  app/src/main/java/com/soi/moya/models/UserPreferences.kt
  app/src/main/java/com/soi/moya/ui/MainActivity.kt
Labels: feature 🌟, done ✅

#67 커스텀 스플래시뷰 삭제
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/soi/moya/base/BaseComposeActivity.kt
  app/src/main/res/drawable/splash_icon.png
  app/src/main/res/drawable/splash_view.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/splash_theme.xml
Labels: feature 🌟, done ✅

#69 #68 - [Chore] 사용하지 않는 코드 삭제
  app/src/main/java/com/soi/moya/HalfModalBottomSheetFragment.kt
  app/src/main/java/com/soi/moya/HomeFragment.kt
  app/src/main/java/com/soi/moya/MusicModel.kt
  app/src/main/java/com/soi/moya/MusicViewModel.kt
  app/src/main/java/com/soi/moya/NoticeBottomSheetFragment.kt
  app/src/main/java/com/soi/moya/PlaySongActivity.kt
  app/src/main/java/com/soi/moya/PlayerSongFragment.kt
  app/src/main/java/com/soi/moya/RecyclerViewAdapter.kt
  app/src/main/java/com/soi/moya/RemoveMainActivity.kt
  app/src/main/java/com/soi/moya/SearchFragment.kt
  app/src/main/java/com/soi/moya/SelectTeamActivity.kt
  app/src/main/java/com/soi/moya/SongListViewAdapter.kt
  app/src/main/java/com/soi/moya/SplashActivity.kt
  app/src/main/java/com/soi/moya/StadiumArrayAdapter.kt
  app/src/main/java/com/soi/moya/StadiumDetailActivity.kt
  app/src/main/java/com/soi/moya/StadiumFragment.kt
  app/src/main/java/com/soi/moya/TeamSongFragment.kt
  app/src/main/java/com/soi/moya/ViewPagerAdapter.kt
  app/src/main/java/com/soi/moya/data/AppContainer.kt
  app/src/main/java/com/soi/moya/data/MusicManager.kt
  app/src/main/java/com/soi/moya/repository/MusicPlayerManager.kt
  app/src/main/java/com/soi/moya/ui/AppViewModelProvider.kt
  app/src/main/java/com/soi/moya/ui/bottom_nav/BottomNavScreen.kt
  app/src/main/java/com/soi/moya/ui/music_list/MusicListViewModel.kt
  app/src/main/java/com/soi/moya/ui/music_player/MusicPlayerScreen.kt
  app/src/main/java/com/soi/moya/ui/music_player/MusicPlayerViewModel.kt
  app/src/main/java/com/soi/moya/ui/splash/SplashScreen.kt
  app/src/main/java/com/soi/moya/util/UiState.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_play_song.xml
  app/src/main/res/layout/activity_select_team.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/activity_stadium_detail.xml
  app/src/main/res/layout/fragment_half_modal_bottom_sheet.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_notice_bottom_sheet.xml
  app/src/main/res/layout/fragment_player_song.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/fragment_stadium.xml
  app/src/main/res/layout/fragment_team_song.xml
  app/src/main/res/layout/list_item_new_featrue.xml
  app/src/main/res/layout/recyclerview_item.xml
  app/src/main/res/layout/request_song_view.xml
  app/src/main/res/layout/song_listview_item.xml
  app/src/main/res/layout/stadium_listview_item.xml
Labels: done ✅

#73 #71 - [Fix] 텍스트 고정 사이즈로 변경
  app/src/main/java/com/soi/moya/ui/Utility.kt
  app/src/main/java/com/soi/moya/ui/theme/MoyaFont.kt
Labels: bug 🐛, done ✅

#74 #72 [Fix] - 음악 중복 재생 이슈
  app/src/main/java/com/soi/moya/repository/MusicPlayerManager.kt
  app/src/main/java/com/soi/moya/ui/music_player/MusicPlayerScreen.kt
  app/src/main/java/com/soi/moya/ui/music_player/MusicPlayerViewModel.kt
Labels: bug 🐛, done ✅
